### ISSUE TITLE
RIPE Atlas Deployment

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#105]
Successfully deploy the RIPE Atlas software agent.

**Comment by junekiwi** [comment]
- https://github.com/Jamesits/docker-ripe-atlas
- https://github.com/RIPE-NCC/ripe-atlas-software-probe
- https://labs.ripe.net/author/alun_davies/ripe-atlas-software-probes/
- https://atlas.ripe.net/docs/software-probe/
> The software probe uses TCP ports 2023 and 8080 internally. If another service is using these ports then the probe will not function correctly.

=> This is **internally**, these ports needs not to be published.

**Comment by junekiwi** [comment]
I setup'ed one probe per node with a DaemonSet.

Each probe must be registered individually (https://atlas.ripe.net/apply/swprobe/). I submitted a registration request for the probe running on the lab's NUC.

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ripe-atlas-probe
  labels:
    app: ripe-atlas-probe
spec:
  selector:
    matchLabels:
      app: ripe-atlas-probe
  template:
    metadata:
      labels:
        app: ripe-atlas-probe
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
      containers:
        - name: ripe-atlas-probe
          image: jamesits/ripe-atlas:latest
          env:
            - name: RXTXRPT
              value: "yes"
          resources:
            limits:
              cpu: 1
              memory: "64Mi"
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_RAW
                - CHOWN
          volumeMounts:
            - name: atlasdata
              mountPath: /var/atlasdata
            - name: atlas-probe-etc
              mountPath: /var/atlas-probe/etc
            - name: atlas-probe-status
              mountPath: /var/atlas-probe/status
      volumes:
        - name: atlasdata
          emptyDir:
            medium: Memory
            sizeLimit: "64Mi"
        - name: atlas-probe-etc
          hostPath:
            path: /var/atlas-probe/etc
        - name: atlas-probe-status
          hostPath:
            path: /var/atlas-probe/status
```
