### ISSUE TITLE
Crash in node contribution controller

### ISSUE THREAD

**Issue by junekiwi** [EdgeNet-project/edgenet-legacy-2024#155]
The controller crashes in https://github.com/EdgeNet-project/edgenet/blob/release-1.0/pkg/util/util.go#L157 because `rawConfig` is empty.

Temporary fix:
```yaml
# kubectl -n edgenet edit deployment nodecontribution
volumeMounts:
# ...
- mountPath: /root/.kube/config
  name: kubeconfig
  readOnly: true
volumes:
# ...
- hostPath:
    path: /root/.kube/config 
  name: kubeconfig
```
